## The dataset I chose is the affairs dataset that comes with Statsmodels. Itwas derived from a survey of women in 1974 by Redbook magazine, inwhich married women were asked about their participation in extramaritalaffairs. More information about the study is available in a 1978 paper fromthe Journal of Political Economy.

## Description of Variables

### The dataset contains 6366 observations of 9 variables:
rate_marriage: woman's rating of her marriage (1 = very poor, 5 =very good)

age: woman's age

yrs_married: number of years married

children: number of children

religious: woman's rating of how religious she is (1 = not religious, 4 =strongly religious)

educ: level of education (9 = grade school, 12 = high school, 14 =some college, 16 = college graduate, 17 = some graduate school, 20= advanced degree)

occupation: woman's occupation (1 = student, 2 = farming/semi-skilled/unskilled, 3 = "white collar", 4 = teacher/nurse/writer/
technician/skilled, 5 = managerial/business, 6 = professional with advanced degree)

occupation_husb: husband's occupation (same coding as above)

affairs: time spent in extra-marital affairs



# Code to loading data and modules:

In [3]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split 
from sklearn import metrics 
from sklearn.model_selection import cross_val_score 
dta = sm.datasets.fair.load_pandas().data

In [4]:
dta

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0               3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1               3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2               4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3               4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4               5.0  27.0          9.0       1.0        1.0  14.0         3.0   
...             ...   ...          ...       ...        ...   ...         ...   
6361            5.0  32.0         13.0       2.0        3.0  17.0         4.0   
6362            4.0  32.0         13.0       1.0        1.0  16.0         5.0   
6363            5.0  22.0          2.5       0.0        2.0  14.0         3.0   
6364            5.0  32.0          6.0       1.0        3.0  14.0         3.0   
6365            4.0  22.0          2.5       0.0        2.0  16.0         2.0   

      occupation_husb   affairs  
0                 5.0  0.111111  
1                 4.0  3.230769  
2                 5.0  1.400000  
3                 5.0  0.727273  
4                 4.0  4.666666  
...               ...       ...  
6361              3.0  0.000000  
6362              5.0  0.000000  
6363              1.0  0.000000  
6364              4.0  0.000000  
6365              4.0  0.000000  

[6366 rows x 9 columns]

In [23]:
dta['affair'] = (dta.affairs >0).astype(int)

In [24]:
dta

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0               3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1               3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2               4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3               4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4               5.0  27.0          9.0       1.0        1.0  14.0         3.0   
...             ...   ...          ...       ...        ...   ...         ...   
6361            5.0  32.0         13.0       2.0        3.0  17.0         4.0   
6362            4.0  32.0         13.0       1.0        1.0  16.0         5.0   
6363            5.0  22.0          2.5       0.0        2.0  14.0         3.0   
6364            5.0  32.0          6.0       1.0        3.0  14.0         3.0   
6365            4.0  22.0          2.5       0.0        2.0  16.0         2.0   

      occupation_husb   affairs  affair  
0                 5.0  0.111111       1  
1                 4.0  3.230769       1  
2                 5.0  1.400000       1  
3                 5.0  0.727273       1  
4                 4.0  4.666666       1  
...               ...       ...     ...  
6361              3.0  0.000000       0  
6362              5.0  0.000000       0  
6363              1.0  0.000000       0  
6364              4.0  0.000000       0  
6365              4.0  0.000000       0  

[6366 rows x 10 columns]

In [25]:
y, X = dmatrices('affair ~ rate_marriage + age + yrs_married + children +  religious + educ + C(occupation) + C(occupation_husb)',dta, return_type="dataframe")

In [26]:
y

affair
0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
...      ...
6361     0.0
6362     0.0
6363     0.0
6364     0.0
6365     0.0

[6366 rows x 1 columns]

In [27]:
X

Intercept  C(occupation)[T.2.0]  C(occupation)[T.3.0]  \
0           1.0                   1.0                   0.0   
1           1.0                   0.0                   1.0   
2           1.0                   0.0                   1.0   
3           1.0                   0.0                   0.0   
4           1.0                   0.0                   1.0   
...         ...                   ...                   ...   
6361        1.0                   0.0                   0.0   
6362        1.0                   0.0                   0.0   
6363        1.0                   0.0                   1.0   
6364        1.0                   0.0                   1.0   
6365        1.0                   1.0                   0.0   

      C(occupation)[T.4.0]  C(occupation)[T.5.0]  C(occupation)[T.6.0]  \
0                      0.0                   0.0                   0.0   
1                      0.0                   0.0                   0.0   
2                      0.0                   0.0                   0.0   
3                      0.0                   1.0                   0.0   
4                      0.0                   0.0                   0.0   
...                    ...                   ...                   ...   
6361                   1.0                   0.0                   0.0   
6362                   0.0                   1.0                   0.0   
6363                   0.0                   0.0                   0.0   
6364                   0.0                   0.0                   0.0   
6365                   0.0                   0.0                   0.0   

      C(occupation_husb)[T.2.0]  C(occupation_husb)[T.3.0]  \
0                           0.0                        0.0   
1                           0.0                        0.0   
2                           0.0                        0.0   
3                           0.0                        0.0   
4                           0.0                        0.0   
...                         ...                        ...   
6361                        0.0                        1.0   
6362                        0.0                        0.0   
6363                        0.0                        0.0   
6364                        0.0                        0.0   
6365                        0.0                        0.0   

      C(occupation_husb)[T.4.0]  C(occupation_husb)[T.5.0]  \
0                           0.0                        1.0   
1                           1.0                        0.0   
2                           0.0                        1.0   
3                           0.0                        1.0   
4                           1.0                        0.0   
...                         ...                        ...   
6361                        0.0                        0.0   
6362                        0.0                        1.0   
6363                        0.0                        0.0   
6364                        1.0                        0.0   
6365                        1.0                        0.0   

      C(occupation_husb)[T.6.0]  rate_marriage   age  yrs_married  children  \
0                           0.0            3.0  32.0          9.0       3.0   
1                           0.0            3.0  27.0         13.0       3.0   
2                           0.0            4.0  22.0          2.5       0.0   
3                           0.0            4.0  37.0         16.5       4.0   
4                           0.0            5.0  27.0          9.0       1.0   
...                         ...            ...   ...          ...       ...   
6361                        0.0            5.0  32.0         13.0       2.0   
6362                        0.0            4.0  32.0         13.0       1.0   
6363                        0.0            5.0  22.0          2.5       0.0   
6364                        0.0            5.0  32.0          6.0       1.0   
6

In [28]:
X = X.rename(columns ={'C(occupation)[T.2.0]':'occ_2',

'C(occupation)[T.3.0]':'occ_3',
'C(occupation)[T.4.0]':'occ_4',
'C(occupation)[T.5.0]':'occ_5',
'C(occupation)[T.6.0]':'occ_6',
'C(occupation_husb)[T.2.0]':'occ_husb_2',
'C(occupation_husb)[T.3.0]':'occ_husb_3',
'C(occupation_husb)[T.4.0]':'occ_husb_4',
'C(occupation_husb)[T.5.0]':'occ_husb_5',
'C(occupation_husb)[T.6.0]':'occ_husb_6'})

In [29]:
X

Intercept  occ_2  occ_3  occ_4  occ_5  occ_6  occ_husb_2  occ_husb_3  \
0           1.0    1.0    0.0    0.0    0.0    0.0         0.0         0.0   
1           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
2           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
3           1.0    0.0    0.0    0.0    1.0    0.0         0.0         0.0   
4           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
...         ...    ...    ...    ...    ...    ...         ...         ...   
6361        1.0    0.0    0.0    1.0    0.0    0.0         0.0         1.0   
6362        1.0    0.0    0.0    0.0    1.0    0.0         0.0         0.0   
6363        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
6364        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
6365        1.0    1.0    0.0    0.0    0.0    0.0         0.0         0.0   

      occ_husb_4  occ_husb_5  occ_husb_6  rate_marriage   age  yrs_married  \
0            0.0         1.0         0.0            3.0  32.0          9.0   
1            1.0         0.0         0.0            3.0  27.0         13.0   
2            0.0         1.0         0.0            4.0  22.0          2.5   
3            0.0         1.0         0.0            4.0  37.0         16.5   
4            1.0         0.0         0.0            5.0  27.0          9.0   
...          ...         ...         ...            ...   ...          ...   
6361         0.0         0.0         0.0            5.0  32.0         13.0   
6362         0.0         1.0         0.0            4.0  32.0         13.0   
6363         0.0         0.0         0.0            5.0  22.0          2.5   
6364         1.0         0.0         0.0            5.0  32.0          6.0   
6365         1.0         0.0         0.0            4.0  22.0          2.5   

      children  religious  educ  
0          3.0        3.0  17.0  
1          3.0        1.0  14.0  
2          0.0        1.0  16.0  
3          4.0        3.0  16.0  
4          1.0        1.0  14.0  
...        ...        ...   ...  
6361       2.0        3.0  17.0  
6362       1.0        1.0  16.0  
6363       0.0        2.0  14.0  
6364       1.0        3.0  14.0  
6365       0.0        2.0  16.0  

[6366 rows x 17 columns]

In [30]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.25,shuffle=True,random_state=40)

In [31]:
x_train.shape

(4774, 17)

In [32]:
x_test.shape

(1592, 17)

In [33]:
model=LogisticRegression()

In [36]:
model.fit(x_train,y_train)

C:\Users\Akshay Gondaliya\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Akshay Gondaliya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [37]:
predict=model.predict(x_test)

In [39]:
predict

array([0., 1., 0., ..., 0., 0., 0.])

In [42]:
metrics.accuracy_score(y_test,predict)

0.7173366834170855

In [66]:
y.values.sum()

2053.0

In [65]:
y_train.values.sum()

1550.0

In [67]:
y_test.values.sum()

503.0

In [68]:
metrics.average_precision_score(y_test,predict)

0.40870039365702193

In [69]:
metrics.precision_score(y_test,predict)

0.5936395759717314

In [70]:
metrics.recall_score(y_test,predict)

0.33399602385685884

In [71]:
metrics.accuracy_score(y_test,predict)

0.7173366834170855

In [75]:
a=model.predict(x_train)


In [76]:
a

array([0., 0., 0., ..., 0., 0., 0.])

In [77]:
metrics.accuracy_score(y_train,a)

0.7274821952241307

In [78]:
metrics.confusion_matrix(y_test,predict)

array([[974, 115],
       [335, 168]], dtype=int64)